# Generated by Django 5.1.2 on 2026-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0045_alter_analogsignalresampled_ia_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='line_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
    ]
